In [1]:
import numpy as np

In [2]:
x = np.array([3, 4, 5])
y = np.array([4, 5, 7])


In [3]:
x + y

array([ 7,  9, 12])

In [4]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [5]:
x.ndim # print dimension

2

In [6]:
x.dtype

dtype('int64')

In [7]:
np.array([[1, 2], [3.0, 4]]).dtype

dtype('float64')

In [8]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if ``__array__`` returns a copy, if obj is a nested
    sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly crea

In [9]:
np.array([[1, 2], [3, 4]], float).dtype

dtype('float64')

In [10]:
x.shape

(2, 2)

In [11]:
x = np.array([1, 2, 3, 4])
x.sum()

10

In [12]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [13]:
x = np.array([1, 2 , 3, 4, 5, 6])
print('begin x: \n', x)
x_reshape = x.reshape((2, 3))
print('reshaped x: \n', x_reshape)

begin x: 
 [1 2 3 4 5 6]
reshaped x: 
 [[1 2 3]
 [4 5 6]]


In [14]:
my_tuple = (3, 4, 5)
my_tuple[2] = 6

TypeError: 'tuple' object does not support item assignment

In [ ]:
x_reshape.shape, x_reshape.ndim, x_reshape.T

((2, 3),
 2,
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [ ]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [ ]:
x ** 2

array([ 1,  4,  9, 16, 25, 36])

In [ ]:
x ** 0.5

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [ ]:
'''
Fucking shit what the fuck is happen in my life, god please help me
'''

In [15]:
np.random.normal?

Docstring:
normal(loc=0.0, scale=1.0, size=None)

Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution, first
derived by De Moivre and 200 years later by both Gauss and Laplace
independently [2]_, is often called the bell curve because of
its characteristic shape (see the example below).

The normal distributions occurs often in nature.  For example, it
describes the commonly occurring distribution of samples influenced
by a large number of tiny, random disturbances, each with its own
unique distribution [2]_.

.. note::
    New code should use the `~numpy.random.Generator.normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
loc : float or array_like of floats
    Mean ("centre") of the distribution.
scale : float or array_like of floats
    Standard deviation (spread or "width") of the distribution. Must be
    non-negative.
size : int 