In [2]:
import numpy as np

In [3]:
x = np.array([3, 4, 5])
y = np.array([4, 5, 7])

In [5]:
x + y 

array([ 7,  9, 12])

In [9]:
x = np.array([[1, 2], [3, 4]])
x 

array([[1, 2],
       [3, 4]])

In [11]:
x.ndim # print dimension

2

In [13]:
x.dtype

dtype('int64')

In [18]:
np.array([[1, 2], [3.0, 4]]).dtype

dtype('float64')

In [19]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if ``__array__`` returns a copy, if obj is a nested
    sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly crea

In [22]:
np.array([[1, 2], [3, 4]], float).dtype

dtype('float64')

In [23]:
x.shape

(2, 2)

In [25]:
x = np.array([1, 2, 3, 4])
x.sum()

10

In [27]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [28]:
x = np.array([1, 2 , 3, 4, 5, 6])
print('begin x: \n', x)
x_reshape = x.reshape((2, 3))
print('reshaped x: \n', x_reshape)

begin x: 
 [1 2 3 4 5 6]
reshaped x: 
 [[1 2 3]
 [4 5 6]]


In [31]:
my_tuple = (3, 4, 5)
my_tuple[2] = 6

TypeError: 'tuple' object does not support item assignment

In [32]:
x_reshape.shape, x_reshape.ndim, x_reshape.T

((2, 3),
 2,
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [33]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [34]:
x ** 2

array([ 1,  4,  9, 16, 25, 36])

In [35]:
x ** 0.5

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])